<div><?php echo $_POST['imagenN'] ?></div>
<img src="./imagenes/<?php echo $_POST['imagenN'] ?>.png" style="height: 10em;">

<!-- 
    JAVASCRIPT NO ANDA PORQUE ES SOLO CLIENTE
    POSIBLEMENTE A LA FECHA SE ENCUENTREN SOLUCIONES CON
    NODEJS O CON UNA API REST JAVASCRIPT

    EL PHP ES UN LENGUAJE QUE SE LEE ANTES QUE TODO EL RESTO
    (PRE HYPERTEXT PROCESSOR) OR (HYPERTEXT PREPROCESSOR)
-->